# Gems
gems:
- jekyll-compass


# Site settings
title:        Mercería Alonso
email:        info@merceriaalonso.com
description:  > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "http://merceriaalonso.com"
timezone:     Europe/Madrid
encoding:     utf-8

# Build settings
markdown:     kramdown


# Collections
collections:
  taller:     # Taller
    output: true
  productos:  # Productos
    output: true


# Compressed layout
compress_html:
  clippings: []
  endings: []